config/routes.rb
Mydevise::Application.routes.draw do
  resources :apps

  resources :clients
  devise_for :sdkusers

end

app/models/app.rb
class App < ActiveRecord::Base
  attr_accessible :internal_auth, :name, :outer_auth_server, :type_interphone, :type_message
end

app/models/client.rb
class Client < ActiveRecord::Base
    attr_accessible :name, :plainPassword, :sip_user, :sip_pass
end   

app/models/group.rb
class Group < ActiveRecord::Base
  attr_accessible :groupName, :description
end

app/models/groupclient.rb
class Groupclient < ActiveRecord::Base
  attr_accessible :groupName, :username,:administrator
end

app/models/groupprop.rb
class Groupprop < ActiveRecord::Base
  attr_accessible :groupName, :name,:propValue
end

app/models/sdkuser.rb
class Sdkuser < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

def after_sign_in_path_for(resource)
  '/pages/admin'
end

end

app/controllers/apps_controller.rb
class AppsController < ApplicationController
   
   layout "sdkuser" 

  # GET /apps
  # GET /apps.json
  def index
    @apps = App.all
    @groups = Group.all
    @groupprops = Groupprop.all
    @groupclients = Groupclient.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @apps }
    end
  end

  # GET /apps/1
  # GET /apps/1.json
  def show
    @app = App.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/new
  # GET /apps/new.json
  def new
    @app = App.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @app }
    end
  end

  # GET /apps/1/edit
  def edit
    @app = App.find(params[:id])
  end

  # POST /apps
  # POST /apps.json
  def create
    @app = App.new(params[:app])

    @group = Group.new
    @group.description = params[:app][:name]
    @group.save

    @groupprop = Groupprop.new
    @groupprop.groupName = params[:app][:name]
    @groupprop.name = 'sharedRoster.displayName'
    @groupprop.propValue = params[:app][:name]
    @groupprop.save
    @groupprop = Groupprop.new
    @groupprop.groupName = params[:app][:name]
    @groupprop.name = 'sharedRoster.groupList'
    @groupprop.propValue = ''
    @groupprop.save
    @groupprop = Groupprop.new
    @groupprop.groupName = params[:app][:name]
    @groupprop.name = 'sharedRoster.showInRoster'
    @groupprop.propValue = 'onlyGroup'
    @groupprop.save

    @groupclient = Groupclient.new
    @groupclient.groupName = params[:app][:name]
    @groupclient.username = ''
    @groupclient.administrator = 1
    @groupclient.save

    @role = Role.new
    @role.name = params[:app][:name]
    @role.save

    respond_to do |format|
      if @app.save
        format.html { redirect_to @app, notice: 'App was successfully created.' }
        format.json { render json: @app, status: :created, location: @app }
      else
        format.html { render action: "new" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apps/1
  # PUT /apps/1.json
  def update
    @app = App.find(params[:id])

    respond_to do |format|
      if @app.update_attributes(params[:app])
        format.html { redirect_to @app, notice: 'App was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @app.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apps/1
  # DELETE /apps/1.json
  def destroy
    @app = App.find(params[:id])
    @app.destroy

    respond_to do |format|
      format.html { redirect_to apps_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  layout "sdkuser"

  # GET /clients
  # GET /clients.json
  def index
    @clients = Client.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @clients }
    end
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
    @client = Client.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/new
  # GET /clients/new.json
  def new
    @client = Client.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @client }
    end
  end

  # GET /clients/1/edit
  def edit
    @client = Client.find(params[:id])
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(params[:client])

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render json: @client, status: :created, location: @client }
      else
        format.html { render action: "new" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /clients/1
  # PUT /clients/1.json
  def update
    @client = Client.find(params[:id])

    respond_to do |format|
      if @client.update_attributes(params[:client])
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client = Client.find(params[:id])
    @client.destroy

    respond_to do |format|
      format.html { redirect_to clients_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/apps_helper.rb
module AppsHelper
end

app/views/apps/_form.html.erb
<%= form_for @app, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :type_message, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :type_message, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :type_interphone, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :type_interphone, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :internal_auth, :class => 'control-label' %>
    <div class="controls">
      <%= f.check_box :internal_auth, :class => 'check_box' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :outer_auth_server, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :outer_auth_server, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                apps_path, :class => 'btn' %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<%- model_class = App -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/apps/index.html.erb
<%- model_class = App -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:type_message) %></th>
      <th><%= model_class.human_attribute_name(:type_interphone) %></th>
      <th><%= model_class.human_attribute_name(:internal_auth) %></th>
      <th><%= model_class.human_attribute_name(:outer_auth_server) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @apps.each do |app| %>
      <tr>
        <td><%= link_to app.id, app_path(app) %></td>
        <td><%= app.name %></td>
        <td><%= app.type_message %></td>
        <td><%= app.type_interphone %></td>
        <td><%= app.internal_auth %></td>
        <td><%= app.outer_auth_server %></td>
        <td><%=l app.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_app_path(app), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      app_path(app),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_app_path,
            :class => 'btn btn-primary' %>


<%- model_class = Group -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:groupName) %></th>
    <th><%= model_class.human_attribute_name(:description) %></th>
  </tr>
  </thead>
  <tbody>
  <% @groups.each do |app| %>
      <tr>
        <td><%= app.groupName %></td>
        <td><%= app.description %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%- model_class = Groupprop -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:groupName) %></th>
    <th><%= model_class.human_attribute_name(:name) %></th>
    <th><%= model_class.human_attribute_name(:propValue) %></th>
  </tr>
  </thead>
  <tbody>
  <% @groupprops.each do |app| %>
      <tr>
        <td><%= app.groupName %></td>
        <td><%= app.name %></td>
        <td><%= app.propValue %></td>
      </tr>
  <% end %>
  </tbody>
</table>

<%- model_class = Groupclient -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
  <tr>
    <th><%= model_class.human_attribute_name(:groupName) %></th>
    <th><%= model_class.human_attribute_name(:username) %></th>
    <th><%= model_class.human_attribute_name(:administrator) %></th>
  </tr>
  </thead>
  <tbody>
  <% @groupclients.each do |app| %>
      <tr>
        <td><%= app.groupName %></td>
        <td><%= app.username %></td>
        <td><%= app.administrator %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/apps/new.html.erb
<%- model_class = App -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/apps/show.html.erb
<%- model_class = App -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @app.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_message) %>:</strong></dt>
  <dd><%= @app.type_message %></dd>
  <dt><strong><%= model_class.human_attribute_name(:type_interphone) %>:</strong></dt>
  <dd><%= @app.type_interphone %></dd>
  <dt><strong><%= model_class.human_attribute_name(:internal_auth) %>:</strong></dt>
  <dd><%= @app.internal_auth %></dd>
  <dt><strong><%= model_class.human_attribute_name(:outer_auth_server) %>:</strong></dt>
  <dd><%= @app.outer_auth_server %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              apps_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_app_path(@app), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              app_path(@app),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

    <div class="field">
      <%= f.label :name %><br />
      <%= f.text_field :name %>
    </div>
    <hr />
    <div class="field">
      <%= f.label :plainPassword %><br />
      <%= f.password_field :plainPassword %>
    </div>
    <div class="field">
      <%= f.label :sip_user %><br />
      <%= f.text_field :sip_user %>
    </div>
    <div class="field">
      <%= f.label :sip_pass %><br />
      <%= f.text_field :sip_pass %>
    </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<h1>Listing clients</h1>

<table>
  <tr>
    <th><%=  Client.human_attribute_name("name") %></th>
    <th><%=  Client.human_attribute_name('plainPassword') %></th>
    <th><%= Client.human_attribute_name('sip_user') %></th>
    <th><%=  Client.human_attribute_name('sip_pass') %></th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @clients.each do |client| %>
  <tr>
    <td><%= client.name %></td>
    <td><%= client.plainPassword %></td>
    <td><%= client.sip_user %></td>
    <td><%= client.sip_pass %></td>
    <td><%= link_to 'Show', client %></td>
    <td><%= link_to 'Edit', edit_client_path(client) %></td>
    <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New client</h1>

<%= render 'form' %>

<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b><%= I18n.t('client.l.name')%>:</b>
  <%= @client.name %>
</p>
<p>
  <b><%= I18n.t('client.l.plainPassword')%>:</b>
  <%= @client.email %>
</p>
<p>
  <b><%= I18n.t('client.l.sip_user')%>:</b>
  <%= @client.sip_user %>
</p>

<p>
  <b><%= I18n.t('client.l.sip_pass')%>:</b>
  <%= @client.sip_pass %>
</p>

<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mydevise</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

    <main role="main">

       <%= yield %>
    </main>


</body>
</html>

app/views/layouts/sdkuser.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Mydevise" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-fluid-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </a>
          

         <!--
          <a class="brand" href="#">Mydevise</a>
          <div class="container-fluid nav-collapse">
            <ul class="nav">
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div> <!--/.nav-collapse -->



            <div class="navbar-collapse collapse">
              <ul class="nav navbar-nav">
                <li class="active"><a href="#">首页</a></li>
                <li><a href="voicemessage.html">语音留言</a></li>
                <li><a href="interphone.html">语音对讲</a></li>
                <li><a href="#contact">视频通话</a></li>  
                <li><a href="interface_doc.html">文档</a></li>      
                <li><a href="#contact">支持</a></li>            
              </ul>
            </div>


        </div>
      </div>
    </div>

    <div class="container-fluid">
      

      <div class="row-fluid">
        <!--
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>
        -->


        <div class="col-sm-3 col-md-2 sidebar">
          <ul class="nav nav-sidebar">
            <li class="active"><a href="/apps/new">创建通讯应用</a></li>
            <li><a href="/apps">应用列表</a></li>
            <li><a href="#"><span style="color: #2a6496;">用户管理<br>
                </span></a></li>
            <li><a href="/clients">Demo帐户</a></li>
          </ul>
          <ul class="nav nav-sidebar">
            <li><a href="">账单</a></li>
            <li><a href=""><span style="color: #2a6496;">支持</span></a></li>
            <li><a href="">API</a></li>
            <li><a href="">设置</a></li>
            <li><a href=""><span style="color: #2a6496;">退出</span></a></li>
          </ul>
        </div>


        <div class="span9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div><!--/row-->
      



      <footer>
        <p>&copy; Company 2014</p>
      </footer>

    </div> <!-- /container -->

  </body>
</html>